### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by dallasgroot** [TryGhost/Edge#13]
Hey there, I got my blog setup and I was wondering how easy it would be to add a dark mode? I’m eager to learn to code so any help would be great.

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!

**Comment by dallasgroot** [comment]
Thanks for directing me to the correct place.
