### ISSUE TITLE
Home page shows broken image icons

### ISSUE THREAD

**Issue by andrewdefries** [TryGhost/Edge#8]
Hello,

I activated your theme and the images from the tags are showing as the broken icon. In the tag area the images show just fine. The dimensions of my images are similar to the original casper theme images which loaded fine before I deleted them.

Please advise and thank you.

**Comment by minimaluminium** [comment]
Hey @andrewdefries,

Could you provide a live URL to your site?

**Comment by andrewdefries** [comment]
Hello,

Thanks for your reply and re-direction to the forum. I appreciate your
response. Got everything working after reading your suggestions.

The URL is here:

http://134.122.9.102/

**Comment by minimaluminium** [comment]
Thanks for getting back with your solution.
